export { gameConfig } from './config'
export { BootScene } from './scenes/BootScene'
export { HouseScene, gameEventBus } from './scenes/HouseScene'
export { UIScene } from './scenes/UIScene'
export { LobsterCharacter } from './characters/LobsterCharacter'
export { RoomManager } from './systems/RoomManager'
export { EventBridge } from './systems/EventBridge'
export { EmotionSystem } from './systems/EmotionSystem'
export { ParticleEffects } from './systems/ParticleEffects'
export { SoundManager } from './systems/SoundManager'
